apiVersion: v1
kind: ConfigMap
metadata:
  name: glamai-config
  namespace: glamai-ns
data:

  
  #backend
  PORT : '5000'
  MONGO_URI : 'mongodb+srv://user-1:user123@gen-ai.dl4pk1r.mongodb.net/users?appName=Gen-ai'
  JWT_SECRET: '123456'

  MODEL_API_URL:  'http://face-api:5000'

  #fortend 
  REACT_APP_API_BASE_URL : '/server/api'

  #model 
  PORT: '8000'
  


 